### ISSUE TITLE
Create event and ticket sale on ti.to

### ISSUE THREAD

**Issue by ams0** [cloudnative-amsterdam/kubernetesdays.amsterdam#2]
Account on tito created, we need to define tickets

**Comment by ticofab** [comment]
Event ready, we need to announce this.

**Comment by ams0** [comment]
link? is it published?

**Comment by ticofab** [comment]
We didn't go live yet but everything is ready for it!

**Comment by ams0** [comment]
we will postpone the ticket sale due to postponing Kubecon

**Comment by ams0** [comment]
will be this one someday: https://ti.to/kubernetes-community-days-amsterdam/kubernetes-community-days-amsterdam-2020
