### ISSUE TITLE
Choose platinum perks

### ISSUE THREAD

**Issue by ams0** [cloudnative-amsterdam/kubernetesdays.amsterdam#4]

**Comment by ams0** [comment]
Some ideas from http://cncf.io/sponsor :

- Flyer chair drop
- Games lounge
- On-stage 5-10 minute pitch
- 150 words communication in pre/post email

**Comment by ams0** [comment]
@ticofab

**Comment by ticofab** [comment]
I would suggest we split these in two so to make it unique:
Platinum Sponsor #1: chain drop + on stage-pitch
Platinum Sponsor #2: games lounge + 150 words in pre/post email
WDYT?

**Comment by ams0** [comment]
Nah I think we can do everything for both (maybe not games lounge, but we're not even sure we have the space).

**Comment by ticofab** [comment]
I feel that two stage pitches and two 150-words email pitches is a lot to force down the attendees.

**Comment by ticofab** [comment]
Decision made during the call, two platinum sponsors will get
* 150-word email pitch (one sponsor in an email before, other sponsor in the mail after)
* 5 minutes stage pitch (one sponsor on the first day, other sponsor on the other day)
* flyer drop on chairs
